import { LightningElement } from "lwc";

export default class calculatorselector extends LightningElement {
  isShowSub=false;
  isShowAdd=false;
  isShowMul=false;
  isShowDiv=false;
    Number1=0
    Number2=0
    Number3=0
    Number4=0
    Number5=0
    Number6=0
    Number7=0
    Number8=0
    Result1
    Result2
    Result3
    Result4

  add(){
    this.isShowAdd=true;
    this.isShowSub=false;
    this.isShowMul=false;
    this.isShowDiv=false;
  }
  sub(){
    this.isShowAdd=false;
    this.isShowSub=true;
    this.isShowMul=false;
    this.isShowDiv=false;
  }
  mul(){
    this.isShowAdd=false;
    this.isShowSub=false;
    this.isShowMul=true;
    this.isShowDiv=false;
  }
  div(){
    this.isShowAdd=false;
    this.isShowSub=false;
    this.isShowMul=false;
    this.isShowDiv=true;
  }
  one(event){
    this.Number1=event.detail.value
  }
  two(event){
    this.Number2=event.detail.value
  }
  three(event){
    this.Number3=event.detail.value
  }
  four(event){
    this.Number4=event.detail.value
  }
  five(event){
    this.Number5=event.detail.value
  }
  six(event){
    this.Number6=event.detail.value
  }
  seven(event){
    this.Number7=event.detail.value
  }
  eight(event){
    this.Number8=event.detail.value
  }
  added(){
    this.Result1=Number(this.Number1)+Number(this.Number2)
  }
  subbed(){
    this.Result2=Number(this.Number3)-Number(this.Number4)
  }
  product(){
    this.Result3=Number(this.Number5)*Number(this.Number6)
  }
  Divide(){
    this.Result4=Number(this.Number7)/Number(this.Number8)
  }

}